// models/StudentMarks.js
const mongoose = require("mongoose");

const studentMarksSchema = new mongoose.Schema(
  {
    prn: {
      type: String,
      required: true,
      trim: true,
    },
    class: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "Class",
      required: [true, "Class Id is requied"],
    },
    subject: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "Subject",
      required: [true, "Subject is required"],
    },
    ut1co1: { type: Number, min: 0, max: 20, default: 0 },
    ut1co2: { type: Number, min: 0, max: 20, default: 0 },
    ut1co3: { type: Number, min: 0, max: 20, default: 0 },
    ut2co4: { type: Number, min: 0, max: 20, default: 0 },
    ut2co5: { type: Number, min: 0, max: 20, default: 0 },
    ut2co6: { type: Number, min: 0, max: 20, default: 0 },
    tw1co1: { type: Number, min: 0, max: 20, default: 0 },
    tw1co2: { type: Number, min: 0, max: 20, default: 0 },
    tw1co3: { type: Number, min: 0, max: 20, default: 0 },
    tw2co1: { type: Number, min: 0, max: 20, default: 0 },
    tw2co2: { type: Number, min: 0, max: 20, default: 0 },
    tw2co3: { type: Number, min: 0, max: 20, default: 0 },
    tw3co1: { type: Number, min: 0, max: 20, default: 0 },
    tw3co2: { type: Number, min: 0, max: 20, default: 0 },
    tw3co3: { type: Number, min: 0, max: 20, default: 0 },
    tw4co1: { type: Number, min: 0, max: 20, default: 0 },
    tw4co2: { type: Number, min: 0, max: 20, default: 0 },
    tw4co3: { type: Number, min: 0, max: 20, default: 0 },
    tw5co1: { type: Number, min: 0, max: 20, default: 0 },
    tw5co2: { type: Number, min: 0, max: 20, default: 0 },
    tw5co3: { type: Number, min: 0, max: 20, default: 0 },
    tw6co1: { type: Number, min: 0, max: 20, default: 0 },
    tw6co2: { type: Number, min: 0, max: 20, default: 0 },
    tw6co3: { type: Number, min: 0, max: 20, default: 0 },
    tw7co1: { type: Number, min: 0, max: 20, default: 0 },
    tw7co2: { type: Number, min: 0, max: 20, default: 0 },
    tw7co3: { type: Number, min: 0, max: 20, default: 0 },
    tw8co1: { type: Number, min: 0, max: 20, default: 0 },
    tw8co2: { type: Number, min: 0, max: 20, default: 0 },
    tw8co3: { type: Number, min: 0, max: 20, default: 0 },
    tw9co1: { type: Number, min: 0, max: 20, default: 0 },
    tw9co2: { type: Number, min: 0, max: 20, default: 0 },
    tw9co3: { type: Number, min: 0, max: 20, default: 0 },
    tw10co1: { type: Number, min: 0, max: 20, default: 0 },
    tw10co2: { type: Number, min: 0, max: 20, default: 0 },
    tw10co3: { type: Number, min: 0, max: 20, default: 0 },
    internalAssessment: { type: Number, min: 0, max: 40, default: 0 },
    pbl: { type: Number, min: 0, max: 20, default: 0 },
    tw: { type: Number, min: 0, max: 100, default: 0 },
    universityExam: { type: Number, min: 0, max: 60, default: 0 },
  },
  { timestamps: true },
);

module.exports = mongoose.model("StudentMarks", studentMarksSchema);
